version: '3.7'

services:
    pg12:
        image: postgres:12-alpine
        container_name: pg12
        volumes:
            - pg12-database:/var/lib/postgresql/data
        ports:
            - 5433:5432
        environment:
            - POSTGRES_PASSWORD=${PG_PASSWORD}
        restart: on-failure

    pg11:
        image: postgres:11-alpine
        container_name: pg11
        volumes:
            - pg11-database:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=${PG_PASSWORD}
        restart: on-failure

    mssql2017:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: mssql2017
        volumes:
            - mssql2017-database:/var/opt/mssql
        ports:
            - 1432:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=${MSSQL_PASSWORD}
            - MSSQL_PID=Developer
        restart: on-failure

volumes:
    pg12-database:
        driver: local
        name: pg12-database

    pg11-database:
        driver: local
        name: pg11-database

    mssql2017-database:
        driver: local
        name: mssql2017-database
